language: android
jdk: oraclejdk8

android:
  components:
    # Tools
    - tools
    - platform-tools
    - build-tools-28.0.0
    # Android SDK
    - android-28

# Cache wipe for Gradle
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

# license agreement
install:
  - echo yes | sdkmanager "tools"
  - echo yes | sdkmanager "platforms;android-28"

# start Gradle without emulator
script:
  - ./gradlew build check