language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.0
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

before_script:
# Prepare pre-accepted licenses to not be promted at installation
  - mkdir -p "$ANDROID_HOME/licenses"
  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"

script:
  - ./gradlew build check

# Cache wipe for Gradle
  before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  cache:
    directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.android/build-cache